"""Initial database schema

Revision ID: 79f114ecea83
Revises: 
Create Date: 2025-08-19 21:17:45.031476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f114ecea83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_info', sa.JSON(), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_usage_date', 'api_usage', ['date'], unique=False)
    op.create_index('idx_api_usage_month', 'api_usage', ['month'], unique=False)
    op.create_index('idx_api_usage_service', 'api_usage', ['service'], unique=False)
    op.create_index('idx_api_usage_success', 'api_usage', ['success'], unique=False)
    op.create_index('idx_api_usage_timestamp', 'api_usage', ['timestamp'], unique=False)
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('state_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('idx_system_state_key', 'system_state', ['key'], unique=False)
    op.create_index('idx_system_state_type', 'system_state', ['state_type'], unique=False)
    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=True),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('quality_metrics', sa.JSON(), nullable=True),
    sa.Column('translator_service', sa.String(length=50), nullable=True),
    sa.Column('cache_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index('idx_cache_accessed', 'translation_cache', ['last_accessed'], unique=False)
    op.create_index('idx_cache_expires', 'translation_cache', ['expires_at'], unique=False)
    op.create_index('idx_cache_key', 'translation_cache', ['cache_key'], unique=False)
    op.create_index('idx_cache_lang_pair', 'translation_cache', ['source_language', 'target_language'], unique=False)
    op.create_table('tweets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_username', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_metrics', sa.JSON(), nullable=True),
    sa.Column('in_reply_to_user_id', sa.String(length=50), nullable=True),
    sa.Column('referenced_tweets', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('tweet_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tweets_author', 'tweets', ['author_id'], unique=False)
    op.create_index('idx_tweets_created_at', 'tweets', ['created_at'], unique=False)
    op.create_index('idx_tweets_processed', 'tweets', ['processed_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('api_credentials', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name')
    )
    op.create_index('idx_users_account_name', 'users', ['account_name'], unique=False)
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_last_active', 'users', ['last_active'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_tweet_id', sa.String(length=50), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('post_id', sa.String(length=50), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_info', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('translation_metadata', sa.JSON(), nullable=True),
    sa.CheckConstraint('status IN ("pending", "posted", "failed", "draft")', name='ck_translation_status'),
    sa.ForeignKeyConstraint(['original_tweet_id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_tweet_id', 'target_language', name='uq_tweet_language')
    )
    op.create_index('idx_translations_created', 'translations', ['created_at'], unique=False)
    op.create_index('idx_translations_status', 'translations', ['status'], unique=False)
    op.create_index('idx_translations_tweet_lang', 'translations', ['original_tweet_id', 'target_language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_translations_tweet_lang', table_name='translations')
    op.drop_index('idx_translations_status', table_name='translations')
    op.drop_index('idx_translations_created', table_name='translations')
    op.drop_table('translations')
    op.drop_index('idx_users_last_active', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.drop_index('idx_users_account_name', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tweets_processed', table_name='tweets')
    op.drop_index('idx_tweets_created_at', table_name='tweets')
    op.drop_index('idx_tweets_author', table_name='tweets')
    op.drop_table('tweets')
    op.drop_index('idx_cache_lang_pair', table_name='translation_cache')
    op.drop_index('idx_cache_key', table_name='translation_cache')
    op.drop_index('idx_cache_expires', table_name='translation_cache')
    op.drop_index('idx_cache_accessed', table_name='translation_cache')
    op.drop_table('translation_cache')
    op.drop_index('idx_system_state_type', table_name='system_state')
    op.drop_index('idx_system_state_key', table_name='system_state')
    op.drop_table('system_state')
    op.drop_index('idx_api_usage_timestamp', table_name='api_usage')
    op.drop_index('idx_api_usage_success', table_name='api_usage')
    op.drop_index('idx_api_usage_service', table_name='api_usage')
    op.drop_index('idx_api_usage_month', table_name='api_usage')
    op.drop_index('idx_api_usage_date', table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
